apiVersion: phase.dev/v1alpha1
kind: PhaseSecret
metadata:
  name: app-secrets
  namespace: app-prod
spec:
  host: https://phase.example.com
  project: changeme-project
  environment: production
  serviceTokenSecretRef:
    name: phase-service-token
    namespace: phase-system
    key: token
  targetSecret:
    name: app-secrets
    namespace: app-prod
