apiVersion: secrets.phase.dev/v1alpha1
kind: PhaseSecret
metadata:
  name: app-secrets
  namespace: app-prod
spec:
  phaseApp: z8
  phaseAppEnv: Production
  phaseHost: https://phase.umami-creative.app
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: phase-service-token
        secretNamespace: phase-system
  managedSecretReferences:
    - secretName: app-secrets
      secretNamespace: app-prod
